PetShelter_StepbyStep_Guide/Controllers/AuthController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PetShelter.Data.Entities;
using PetShelter.Shared;
using PetShelter.Shared.Dtos;
using PetShelter.Shared.Enums;
using PetShelter.Shared.Security;
using PetShelter.Shared.Services.Contracts;
using PetShelter_StepbyStep_Guide.ViewModels;
using System.Security.Claims;
using System.Threading.Tasks;

namespace PetShelter_StepbyStep_Guide.Controllers
{
    [AllowAnonymous]
    public class AuthController : Controller
    {
        private readonly IUserServices usersService;
        private readonly IRoleServices rolesService;
        private readonly IMapper mapper;
        public AuthController(IUserServices usersService,
            IRoleServices rolesService,
                IMapper mapper)
        {
            this.usersService = usersService;
            this.rolesService = rolesService;
            this.mapper = mapper;
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login([FromForm] LoginVM model)
        {
            string loggedUsername = User.FindFirst(ClaimTypes.Name)?.Value;
            if (loggedUsername != null)
            {
                return Forbid();
            }
            if (!await this.usersService.CanUserLoginAsync(model.Username, model.Password))
            {
                return BadRequest(Constants.InvalidCredentials);
            }
            await LoginUser(model.Username);
            return RedirectToAction(nameof(HomeController.Index), "home");
        }
        private async Task LoginUser(string username)
        {
            var user = await this.usersService.GetByUsernameAsync(username);
            var claims = new[]
            {
                new Claim(ClaimTypes.Name,user.Username),
                new Claim(ClaimTypes.Role,user.Role.Name),
            };
            var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var principal = new ClaimsPrincipal(identity);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

        }
        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register([FromForm] RegisterVM userCreateModel)
        {
            string loggedUsername = User.FindFirst(ClaimTypes.Name)?.Value;
            if (loggedUsername != null)
            {
                return Forbid();
            }
            if (await this.usersService.GetByUsernameAsync(userCreateModel.Username) != default)
            {
                return BadRequest(Constants.UserAlreadyExists);
            }
            var hasherPassword = PasswordHasher.HashPassword(userCreateModel.Password);
            userCreateModel.Password = hasherPassword;
            var userDto = this.mapper.Map<UserDto>(userCreateModel);
            userDto.RoleId = (await rolesService.GetByNameIfExistsAsync(UserRole.User.ToString()))?.Id;
            await this.usersService.SaveAsync(userDto);
            await LoginUser(userDto.Username);
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }
        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            string loggedUsername = User.FindFirst(ClaimTypes.Name)?.Value;
            if (loggedUsername != null)
            {
                await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            }
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }
    }
}

PetShelter_StepbyStep_Guide/Controllers/PetController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using PetShelter.Services;
using PetShelter.Shared.Dtos;
using PetShelter.Shared.Repos.Contracts;
using PetShelter.Shared.Services.Contracts;
using PetShelter_StepbyStep_Guide.ViewModels;

namespace PetShelter_StepbyStep_Guide.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = "Admin, Employee, User")]
    public class PetController : BaseCrudController<PetDto, IPetRepository, IPetServices, PetEditVM, PetDetailsVM>
    {
        public PetController(PetService service, IMapper mapper) : base(service, mapper)
        {

        }
    }
}

PetShelter_StepbyStep_Guide/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using PetShelter.Shared.Enums
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PetShelter</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PetShelter.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PetShelter</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (Context.User?.FindFirst(ClaimTypes.Role)?.Value == UserRole.Employee.ToString() ||
                        Context.User?.FindFirst(ClaimTypes.Role)?.Value == UserRole.Admin.ToString())
                        {
                            <li class=" nav-item">
                                <a class=" nav-link text-dark" asp-area="" asp-controller="Breed" asp-action="List">Breeds</a>
                            </li>
                        }
                        @if (Context.User?.FindFirst(ClaimTypes.Role)?.Value == UserRole.Employee.ToString() ||
                        Context.User?.FindFirst(ClaimTypes.Role)?.Value == UserRole.Admin.ToString())
                        {
                            <li class=" nav-item">
                                <a class=" nav-link text-dark" asp-area="" asp-controller="Location" asp-action="List">Locations</a>
                            </li>
                        }
                        @if (Context.User?.FindFirst(ClaimTypes.Role)?.Value == UserRole.Employee.ToString() ||
                        Context.User?.FindFirst(ClaimTypes.Role)?.Value == UserRole.Admin.ToString())
                        {
                            <li class=" nav-item">
                                <a class=" nav-link text-dark" asp-area="" asp-controller="Pet" asp-action="List">Pets</a>
                            </li>
                        }
                        @if (Context.User?.FindFirst(ClaimTypes.Role)?.Value == UserRole.Employee.ToString() ||
                        Context.User?.FindFirst(ClaimTypes.Role)?.Value == UserRole.Admin.ToString())
                        {
                            <li class=" nav-item">
                                <a class=" nav-link text-dark" asp-area="" asp-controller="PetType" asp-action="List">PetTypes</a>
                            </li>
                        }
                        @if (Context.User?.FindFirst(ClaimTypes.Role)?.Value == UserRole.Employee.ToString() ||
                        Context.User?.FindFirst(ClaimTypes.Role)?.Value == UserRole.Admin.ToString())
                        {
                            <li class=" nav-item">
                                <a class=" nav-link text-dark" asp-area="" asp-controller="PetVaccine" asp-action="List">PetVaccines</a>
                            </li>
                        }
                        @if (Context.User?.FindFirst(ClaimTypes.Role)?.Value == UserRole.Employee.ToString() ||
                        Context.User?.FindFirst(ClaimTypes.Role)?.Value == UserRole.Admin.ToString())
                        {
                            <li class=" nav-item">
                                <a class=" nav-link text-dark" asp-area="" asp-controller="Role" asp-action="List">Roles</a>
                            </li>
                        }
                        @if (Context.User?.FindFirst(ClaimTypes.Role)?.Value == UserRole.Employee.ToString() ||
                        Context.User?.FindFirst(ClaimTypes.Role)?.Value == UserRole.Admin.ToString())
                        {
                            <li class=" nav-item">
                                <a class=" nav-link text-dark" asp-area="" asp-controller="Shelter" asp-action="List">Shelters</a>
                            </li>
                        }
                        @if (Context.User?.FindFirst(ClaimTypes.Role)?.Value == UserRole.Employee.ToString() ||
                        Context.User?.FindFirst(ClaimTypes.Role)?.Value == UserRole.Admin.ToString())
                        {
                            <li class=" nav-item">
                                <a class=" nav-link text-dark" asp-area="" asp-controller="User" asp-action="List">Users</a>
                            </li>
                        }
                        @if (Context.User?.FindFirst(ClaimTypes.Role)?.Value == UserRole.Employee.ToString() ||
                        Context.User?.FindFirst(ClaimTypes.Role)?.Value == UserRole.Admin.ToString())
                        {
                            <li class=" nav-item">
                                <a class=" nav-link text-dark" asp-area="" asp-controller="Vaccine" asp-action="List">Vaccine</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PetShelter - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>